//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.24 at 11:48:00 AM EEST 
//


package com.example.demo.models;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.demo.models package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.demo.models
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link ReportingTableType }
     * 
     */
    public ReportingTableType createReportingTableType() {
        return new ReportingTableType();
    }

    /**
     * Create an instance of {@link TransientValueType }
     * 
     */
    public TransientValueType createTransientValueType() {
        return new TransientValueType();
    }

    /**
     * Create an instance of {@link KeyType }
     * 
     */
    public KeyType createKeyType() {
        return new KeyType();
    }

    /**
     * Create an instance of {@link KeyType.DimensionInstances }
     * 
     */
    public KeyType.DimensionInstances createKeyTypeDimensionInstances() {
        return new KeyType.DimensionInstances();
    }

    /**
     * Create an instance of {@link NodeCommentType }
     * 
     */
    public NodeCommentType createNodeCommentType() {
        return new NodeCommentType();
    }

    /**
     * Create an instance of {@link RecordType }
     * 
     */
    public RecordType createRecordType() {
        return new RecordType();
    }

    /**
     * Create an instance of {@link VariableType }
     * 
     */
    public VariableType createVariableType() {
        return new VariableType();
    }

    /**
     * Create an instance of {@link Data.Metadata }
     * 
     */
    public Data.Metadata createDataMetadata() {
        return new Data.Metadata();
    }

    /**
     * Create an instance of {@link Data.Metadata.DimensionInstances }
     * 
     */
    public Data.Metadata.DimensionInstances createDataMetadataDimensionInstances() {
        return new Data.Metadata.DimensionInstances();
    }

    /**
     * Create an instance of {@link Data.Party }
     * 
     */
    public Data.Party createDataParty() {
        return new Data.Party();
    }

    /**
     * Create an instance of {@link Data.Submission }
     * 
     */
    public Data.Submission createDataSubmission() {
        return new Data.Submission();
    }

    /**
     * Create an instance of {@link Data.Variables }
     * 
     */
    public Data.Variables createDataVariables() {
        return new Data.Variables();
    }

    /**
     * Create an instance of {@link Data.NodeComments }
     * 
     */
    public Data.NodeComments createDataNodeComments() {
        return new Data.NodeComments();
    }

    /**
     * Create an instance of {@link Data.TransientValues }
     * 
     */
    public Data.TransientValues createDataTransientValues() {
        return new Data.TransientValues();
    }

    /**
     * Create an instance of {@link Data.ReportingTables }
     * 
     */
    public Data.ReportingTables createDataReportingTables() {
        return new Data.ReportingTables();
    }

    /**
     * Create an instance of {@link CommentType }
     * 
     */
    public CommentType createCommentType() {
        return new CommentType();
    }

    /**
     * Create an instance of {@link YearType }
     * 
     */
    public YearType createYearType() {
        return new YearType();
    }

    /**
     * Create an instance of {@link YearSpecificCommentType }
     * 
     */
    public YearSpecificCommentType createYearSpecificCommentType() {
        return new YearSpecificCommentType();
    }

    /**
     * Create an instance of {@link NodeType }
     * 
     */
    public NodeType createNodeType() {
        return new NodeType();
    }

    /**
     * Create an instance of {@link BaseRecordType }
     * 
     */
    public BaseRecordType createBaseRecordType() {
        return new BaseRecordType();
    }

    /**
     * Create an instance of {@link TransientYearType }
     * 
     */
    public TransientYearType createTransientYearType() {
        return new TransientYearType();
    }

    /**
     * Create an instance of {@link TransientRecordType }
     * 
     */
    public TransientRecordType createTransientRecordType() {
        return new TransientRecordType();
    }

    /**
     * Create an instance of {@link UserCreatedTransientType }
     * 
     */
    public UserCreatedTransientType createUserCreatedTransientType() {
        return new UserCreatedTransientType();
    }

    /**
     * Create an instance of {@link CellType }
     * 
     */
    public CellType createCellType() {
        return new CellType();
    }

    /**
     * Create an instance of {@link ReportingTableType.Cells }
     * 
     */
    public ReportingTableType.Cells createReportingTableTypeCells() {
        return new ReportingTableType.Cells();
    }

    /**
     * Create an instance of {@link TransientValueType.Years }
     * 
     */
    public TransientValueType.Years createTransientValueTypeYears() {
        return new TransientValueType.Years();
    }

    /**
     * Create an instance of {@link TransientValueType.UserCreatedValues }
     * 
     */
    public TransientValueType.UserCreatedValues createTransientValueTypeUserCreatedValues() {
        return new TransientValueType.UserCreatedValues();
    }

    /**
     * Create an instance of {@link KeyType.DimensionInstances.DimensionInstance }
     * 
     */
    public KeyType.DimensionInstances.DimensionInstance createKeyTypeDimensionInstancesDimensionInstance() {
        return new KeyType.DimensionInstances.DimensionInstance();
    }

    /**
     * Create an instance of {@link NodeCommentType.YearSpecificComments }
     * 
     */
    public NodeCommentType.YearSpecificComments createNodeCommentTypeYearSpecificComments() {
        return new NodeCommentType.YearSpecificComments();
    }

    /**
     * Create an instance of {@link RecordType.Comments }
     * 
     */
    public RecordType.Comments createRecordTypeComments() {
        return new RecordType.Comments();
    }

    /**
     * Create an instance of {@link VariableType.Years }
     * 
     */
    public VariableType.Years createVariableTypeYears() {
        return new VariableType.Years();
    }

    /**
     * Create an instance of {@link VariableType.Comments }
     * 
     */
    public VariableType.Comments createVariableTypeComments() {
        return new VariableType.Comments();
    }

    /**
     * Create an instance of {@link Data.Metadata.Nodes }
     * 
     */
    public Data.Metadata.Nodes createDataMetadataNodes() {
        return new Data.Metadata.Nodes();
    }

    /**
     * Create an instance of {@link Data.Metadata.Keys }
     * 
     */
    public Data.Metadata.Keys createDataMetadataKeys() {
        return new Data.Metadata.Keys();
    }

    /**
     * Create an instance of {@link Data.Metadata.DimensionInstances.DimensionInstance }
     * 
     */
    public Data.Metadata.DimensionInstances.DimensionInstance createDataMetadataDimensionInstancesDimensionInstance() {
        return new Data.Metadata.DimensionInstances.DimensionInstance();
    }

}
