//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.24 at 11:48:00 AM EEST 
//


package com.example.demo.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 year specific comments are node commens, which are only defined for specific years
 *             
 * 
 * <p>Java class for yearSpecificCommentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="yearSpecificCommentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}commentType"&gt;
 *       &lt;attribute name="yearName" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "yearSpecificCommentType")
public class YearSpecificCommentType
    extends CommentType
{

    @XmlAttribute(name = "yearName", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String yearName;

    /**
     * Gets the value of the yearName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYearName() {
        return yearName;
    }

    /**
     * Sets the value of the yearName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYearName(String value) {
        this.yearName = value;
    }

}
